/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#FEF8FA',
        foreground: '#1A0812',
        card: '#FFFFFF',
        'card-foreground': '#1A0812',
        popover: '#FFFFFF',
        'popover-foreground': '#1A0812',
        primary: '#E8127A',
        'primary-foreground': '#FFFFFF',
        secondary: '#FDE8F0',
        'secondary-foreground': '#1A0812',
        muted: '#FFF5F8',
        'muted-foreground': '#8A5A6E',
        accent: '#FF69B4',
        'accent-foreground': '#FFFFFF',
        destructive: '#D4183D',
        'destructive-foreground': '#FFFFFF',
        border: 'rgba(232, 18, 122, 0.12)',
        input: 'transparent',
        'input-background': '#FEF0F5',
        ring: 'rgba(232, 18, 122, 0.35)',
        success: '#4CAF50',
        warning: '#FF9800',
        error: '#EF4444',
        rose: {
          50: '#FFF0F5',
          100: '#FFE0EC',
          200: '#FFB3C6',
          300: '#FF85A2',
          400: '#FF5C8A',
          500: '#E8127A',
          600: '#D01679',
          700: '#A80F5E',
          800: '#800A47',
          900: '#5A0631',
        },
        surface: '#FFFFFF',
        'surface-foreground': '#1A0812',
        studio: '#EC1A66',
      },
      fontFamily: {
        sans: ['DM Sans', 'system-ui', 'sans-serif'],
        display: ['Playfair Display', 'serif'],
        script: ['Dancing Script', 'cursive'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      spacing: {
        18: '4.5rem',
        88: '22rem',
        112: '28rem',
        128: '32rem',
      },
      borderRadius: {
        sm: 'calc(0.625rem - 4px)',
        md: 'calc(0.625rem - 2px)',
        lg: '0.625rem',
        xl: 'calc(0.625rem + 4px)',
        '4xl': '2rem',
        '5xl': '2.5rem',
        polaroid: '0.5rem',
      },
      backdropBlur: {
        xs: '2px',
      },
      boxShadow: {
        polaroid: '0 4px 20px rgba(232, 18, 122, 0.12)',
        sticker: '2px 3px 12px rgba(232, 18, 122, 0.18)',
        soft: '0 2px 20px rgba(232, 18, 122, 0.08)',
        glow: '0 0 30px rgba(232, 18, 122, 0.2)',
        card: '0 4px 32px rgba(26, 8, 18, 0.06)',
        nav: '0 2px 24px rgba(26, 8, 18, 0.08)',
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease-in-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        countdown: 'countdown 1s ease-in-out',
        float: 'float 6s ease-in-out infinite',
        'float-slow': 'float 9s ease-in-out infinite',
        'float-fast': 'float 4s ease-in-out infinite',
        'bounce-soft': 'bounceSoft 2s ease-in-out infinite',
        wiggle: 'wiggle 1s ease-in-out infinite',
        'pulse-pink': 'pulsePink 2s ease-in-out infinite',
        marquee: 'marquee 30s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(24px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.92)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        countdown: {
          '0%': { transform: 'scale(1.3)', opacity: '0' },
          '40%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.7)', opacity: '0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(var(--rot, 0deg))' },
          '50%': { transform: 'translateY(-10px) rotate(var(--rot, 0deg))' },
        },
        bounceSoft: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-4deg)' },
          '50%': { transform: 'rotate(4deg)' },
        },
        pulsePink: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(232,18,122,0.3)' },
          '50%': { boxShadow: '0 0 0 12px rgba(232,18,122,0)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
    },
  },
  plugins: [],
}
